version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/risk-tool
hooks:
  BeforeInstall:
    - location: aws/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/after_install.sh
      timeout: 3600
      runas: root
