export { default as logo } from "./images/logo.png";
export { default as avatar } from "./images/avatar.png";
export { default as truck } from "./images/truck.png";
export { default as truckDark } from "./images/truck-dark.png";
export { default as destinationIcon } from "./images/destination.svg";
export { default as originIcon } from "./images/origin.svg";
export { default as alertIcon } from "./images/alert-icon.png";
export { default as homeTruck1 } from "./images/home-truck1.png";
export { default as companyIcon } from "./images/company-icon.png";
