name: Test

on:
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      JWT_ACCESS: ${{ secrets.JWT_ACCESS }}
      JWT_REFRESH: ${{ secrets.JWT_REFRESH }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
      VITE_GOOGLE_KEY: ${{ secrets.VITE_GOOGLE_KEY }}

    strategy:
      matrix:
        node: [16.x]
        mongodb: [5.0]
        python: [3.9]

    name: Test - Node ${{ matrix.node }} - Mongo ${{ matrix.mongodb }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: |
          pip install wheel
          pip install numpy matplotlib
          pip install -U scikit-fuzzy
      - name: Install node dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
